### ISSUE TITLE
Just wondering

### ISSUE THREAD

**Issue by Nexotap** [sabre-io/davclient#19]
I'm just wondering why this project is like abandoned. I was looking for a davclient for php but there's not much around. While sabre has a very good server I was looking here, but since 8 years nothing? Why? Are there other solutions or is there just no need for something like this?

**Comment by DeepDiver1975** [comment]
I'd say there is no need ....

**Comment by staabm** [comment]
Agree

**Comment by evert** [comment]
I wrote the majority of this in an afternoon almost a decade ago. You're literally one of the first to ask about this :P

I think there's a library called 'flysystem' that has a WebDAV client?

**Comment by frankdejonge** [comment]
Hi Evert,

That was actually a Flysystem adapter that was using this exact library under the hood 😅

**Comment by Nexotap** [comment]
I'm happy I could bring back some memories 😂.

Unfortunately a decade ago I had no need for something like this. 
Maybe im getting to old for this.  But what are people using this days when they want to receive caldav stuff?  Do they just code something from scratch or try to not use it at all because it's too cumbersome?

**Comment by evert** [comment]
If you're doing CalDAV, i'd say it might still be a pain in the ass and could be worth re-using some of the libraries from sabre/dav (the main project). Specifically, the libraries for parsing the XML responses.

A lot of these have serializers and deserializers, with the intent that they can be used both for the client and server use-cases. For example:

https://github.com/sabre-io/dav/blob/master/lib/DAV/Xml/Response/MultiStatus.php

Other than the stuff that deals with the formats, presumably you could use any old HTTP client.

**Comment by Nexotap** [comment]
Is see. Well, I will then close this issue.
Thank you alot for the answers.
